name: Release

on:
    workflow_run:
        workflows: [main]
        types:
            - completed
    push:
        branches: [main]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: release
              run: |
                npm ci 
                npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ github.token }}
